### ISSUE TITLE
I want big and HD menu icons

### ISSUE THREAD

**Issue by arteze** [lxde/lxpanel#85]
In __gtk.css__ I managed to increase the size of the icons using `scale(2)`, but only the image is resized, it does not load the icons in good resolution.

__/root/.config/gtk-3.0/gtk.css__
```css
menuitem {
    min-width: 1px;
}
menuitem image {
	-gtk-icon-transform: scale(2);
    min-width: 32px;
	margin-right: 12px;
}
```

The path where I have the icons would be this (and others).
 - /usr/share/icons/flat-remix/apps/scalable

![Captura de pantalla(1)](https://github.com/user-attachments/assets/e06716f8-7120-40a3-98d6-5668c9bfedee)
